In [14]:
# Eigen Values & Eigen Vectors 
# When a vector remain on same vector space either by strething or squeezing it's eigen vector
# Eigen vector a unit vector
# The value by which it is squished or stretched is eigen values
# A*V = lamda*V
# A*V = (lamda*I)*V
# [A-(lambda*I)]*V = 0 
# det([A-(lambda*I)]) = 0
# No real solutions mean no eigen vectors
# There can be multiple eigenvectors with a single eigen value

# Eigen basis is used to ease down the matrix operations. It rotates the axis itself.
# i-hat [-1  j-hat [0
#        0]         2]
# All Eigen basis are eigen vectors and a digonal matrix. Diagonal values representing 
# the eigen values.
# If non-zero non diagonal values then change coordinate sytem itself
# Use eigen vector as basis matrix then [B^-1][C][B] = Eigenbasis(New Diagonal Matrix)
# Solve for this and then convert back to get result
import numpy as np

# A = np.array([0,0]*3)
# v = np.array([0,0]*3)
# l = np.random.random() 
# A.dot(v) = l*v
# # Q = solution for A-LI ke solution  
# A = Q.dot(diag(v)).dot(Q**-1)

# EIGENDECOMPOSITION 
A = np.array([[1,2,3,],[4,5,6,],[7,8,9]])
values, vectors = np.linalg.eig(A)
print 'eigen values: %s'%values
print 'eigen vectors: %s'%vectors

B = A.dot(vectors[:,0])
print(B)

# C = vectors

eigen values: [  1.61168440e+01  -1.11684397e+00  -1.30367773e-15]
eigen vectors: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[-0.23197069 -0.52532209 -0.8186735 ]
[ -3.73863537  -8.46653421 -13.19443305]


In [8]:
# PRINCIPAL COMPONENT ANALYSIS 
# Projection of actual data with same or fewer number of dimensions
# When m-cloumns are projected(copied) into subspace with m or fewer columns

# Steps
#--------
# A = dataset(n x m)
# B = PCA(A)
# [Calculate mean of each column of A] =  M
# [covariance matrix of centered matrix C] = C = A - M
# Covariance matrix is always a symmetric matrix
# [Covariance matrix is relation of every column with every other column.] = V = cov(C)
# Calculate Eigen-decomposition of V = Values, Vectors = eig(V)

# If eigenvalues are similar then we existing vector is reasonably compressed
# If eigenvalues close to 0 discard them
# [Select K eigen vectors] k <= m  
# These are k principal components with k largest values
# B = select(values,vectors)
# P = B^T . A

# FROM SCRATCH
import numpy as np

# Define Matrix 
A = np.array([[1,2],[3,4],[5,6]])
print A
print '-'*45

# Calculate Mean for each column
M = np.mean(A.T, axis=1)
print M
print '-'*45

# Center the column by subtracting the means
C = A - M
print C
print '-'*45

# Calculate covariance matrix of centered matrix
V = np.cov(C.T)
print V
print '-'*45

# Eigendecomposition of V
values, vectors = np.linalg.eig(V)
print vectors
print values
print '-'*45

# Project Data
P = vectors.T.dot(C.T)
print P.T
print '='*45


# USING THE LIBRARY
from sklearn.decomposition import PCA
A = np.array([[1,2],[3,4],[5,6]])
pca = PCA(2)
pca.fit(A)
print pca.components_
print pca.explained_variance_
B = pca.transform(A)
print B

[[1 2]
 [3 4]
 [5 6]]
---------------------------------------------
[ 3.  4.]
---------------------------------------------
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
---------------------------------------------
[[ 4.  4.]
 [ 4.  4.]]
---------------------------------------------
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[ 8.  0.]
---------------------------------------------
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[ 8.  0.]
[[ -2.82842712e+00  -2.22044605e-16]
 [  0.00000000e+00   0.00000000e+00]
 [  2.82842712e+00   2.22044605e-16]]


In [ ]:
# SVD